// export const apiBaseUrl = "https://medh-backend.vercel.app/api/v1";  //vercel URL
export const apiBaseUrl = "https://13.202.119.19.nip.io/api/v1"; //live instance URL
// export const apiBaseUrl = "http://localhost:8080/api/v1"; // local URL

export const apiUrls = {
  user: {
    register: "/auth/register",
    login: "/auth/login",
    update: "/auth/update",
    delete: "/auth/delete",
    getDetailsbyId: "/auth/get",
    getAll: "/auth/get-all",
    updateByEmail: "/auth/update-by-email",
    toggleStudentStatus: "/auth/toggle-status",
    sendResetEmail: "/auth/forgot-password",
    verfiySystemPassword: "/auth//verify-temp-password",
    resetPassword: "/auth/reset-password",
  },
  courses: {
    getAllCoursesWithLimits: (
      page = 1,
      limit = 10,
      course_title,
      course_tag,
      course_category,
      status,
      search,
      course_grade,
      category
    ) =>
      `/courses/getLimitedCourses?page=${page}&limit=${limit}&course_title=${course_title}&course_tag=${course_tag}&course_category=${course_category}&status=${status}&search=${search}&course_grade=${course_grade}&category=${category}`,
    getAllCourses: "/courses/get",
    getCourseById: "/courses/get",
    createCourse: "/courses/create",
    updateCourse: "/courses/update",
    deleteCourse: "/courses/delete",
    getCourseNames: "/courses/course-names",
    getEnrolledCoursesByStudentId: "/enroll/student",
    toggleCourseStatus: "/courses/toggle-status",
    addRecordedVideos: "/courses/recorded-videos",
    getRecorderVideosForUser:"/courses/recorded-videos"
  },
  upload: {
    uploadImage: "/upload/uploadImage",
    uploadMedia: "/upload/uploadMedia",
    uploadDocument: "/upload/uploadDocument",
  },
  onlineMeeting: {
    createMeeting: "/online-meeting/create",
    getAllMeetings: "/online-meeting/get",
    getMeetingDetails: "/online-meeting/get/:id",
    updateMeeting: "/online-meeting/update/:id",
    deleteMeeting: "/online-meeting/delete/:id",
    getMeetingByStudentId: "/online-meeting/student",
    getMeetingsByInstructorId: "/online-meeting/upcoming-classes",
  },
  // Instructor: {
  //   getAllInstructors: "/instructors/get",
  //   getInstructorById: "/instructors/get",
  //   createInstructor: "/instructors/create",
  //   updateInstructor: "/instructors/update/:id",
  //   deleteInstructor: "/instructors/delete",
  //   toggleInstructorsStatus: "/instructors/toggle-status",
  // },
  Instructor: {
    getAllInstructors: "/auth/get-all-instrucors",
    getInstructorById: "/auth/get-instructor",
    createInstructor: "/auth/create",
    updateInstructor: "/auth/updateInstrucor/:id",
    deleteInstructor: "/auth/delete-instrucor",
    toggleInstructorsStatus: "/auth/toggle-status-instrucor",
  },
  Students: {
    getAllStudents: "/students/get",
    getStudentById: "/students/get/:id",
    createStudent: "/students/create",
    updateStudent: "/students/update/:id",
    deleteStudent: "/students/delete",
    // toggleStudentStatus: "/students/toggle-status",
  },
  Contacts: {
    getAllContacts: "/contact/get",
    getContactById: "/contact/get/:id",
    createContact: "/contact/create",
    updateContact: "/contact/update/:id",
    deleteContact: "/contact/delete",
  },
  enrollWebsiteform: {
    createEnrollWebsiteForm: "/enroll-form/create",
    getAllEnrollWebsiteForms: "/enroll-form/getAll",
    getEnrollWebsiteFormById: "/enroll-form/get/:id",
    updateEnrollWebsiteForm: "/enroll-form/update/:id",
    deleteEnrollWebsiteForm: "/enroll-form/delete",
  },
  Blogs: {
    getAllBlogs: "/blogs/get",
    getBlogById: "/blogs/get/:id",
    createBlog: "/blogs/create",
    updateBlog: "/blogs/update/:id",
    deleteBlog: "/blogs/delete",
  },
  adminDashboard: {
    getDashboardCount: "/dashboard/admin-dashboard-count",
  },
  assignedInstructors: {
    getAllAssignedInstructors: "/assigned-instrutors/assigned",
    getAssignedInstructorById: "/assigned-instrutors/get",
    createAssignedInstructor: "/assigned-instrutors/create",
    updateAssignedInstructor: "/assigned-instrutors/update",
    deleteAssignedInstructor: "/assigned-instrutors/delete",
  },
  placements: {
    addPlacements: "/placements/create",
    getPlacements: "/placements/getAll",
  },
  quzies: {
    getQuizes: "/quizes",
    uploadQuizes: "/quizes/upload",
    quizResponses:"/quizResponses",
    getQuizResponses:"/quizResponses/responses",
    getQuizesById: "/quizes/get",
  },
  assignments: {
    addAssignments: "/assignments/create",
    getAssignments: "/assignments",
    submitAssignments: "/assignments/submit",
    submittedAssignments: "/assignments/submitted/get",
    assignmentsStatus: "/assignments/submition/status",
    assignmentsCountByInstructorId: "/assignments/submitted-assignments-count",
    getAssignmentsByEnrolledCourses: "/assignments/enrolled-assignments",
  },
  feedbacks: {
    createFeedback: "/feedback/",
    getAllFeedbacks: "/feedback/getAll",
    deleteFeedback: "/feedback/delete-feedback",
    createComplaint: "/complaint/",
    getAllComplaints: "/complaint",
    deleteComplaint: "/complaint/delete",
    updateComplaintStatus: "/complaint/change-status",
    instructorFeedback: "/feedback/instructor/add",
    getAllInstructorFeedbacks: "/feedback/getAll/instructors-feedbacks",
    deleteInstructorFeedback: "/feedback/instructor",
  },
  resources: {},
  categories: {
    getAllCategories: "/categories/getAll",
    getCategoriesById: "/categories/get/:id",
    createCategories: "/categories/create",
    updateCategories: "/categories/update",
    deleteCategories: "/categories/delete",
  },
  EnrollCourse: {
    enrollCourse: "/enroll/create",
    getEnrolledCourse: "/enroll/getAll",
    getCountByStudentId: "/enroll/getCount",
    getEnrolledCourseById: "/enroll/get",
    getEnrolledCoursesByStudentId: "/enroll/student",
    getUpcomingCoursesByStudentId: "/enroll/get-upcoming-meetings",
    getEnrolledStudentsByCourseId: "/enroll/course",
    watchModule: "/enroll/watch",
  },
  Subscription: {
    AddSubscription: "/subscription/create",
    getSubscription: "/subscription/getAll",
    getSubscriptionById: "/subscription/get",
    getEnrollmentStatus: "/subscription/enrollStatus",
    updateSubscription: "/subscription/update",
    deleteSubscription: "/subscription/delete",
    getAllSubscriptionByStudentId: "/subscription/get-subscription",
  },
  Membership: {
    addMembership: "/memberships/create",
    getMembership: "/memberships/getAll",
    getMembershipById: "/memberships/get",
    renewMembershipById: "/memberships/renew",
    updateMembership: "/memberships/update",
    deleteMembership: "/memberships/delete",
    getSelfPackedCount: "/memberships/membership-count",
    getMembershipBbyStudentId: "/memberships/getmembership",
  },
  jobForm: {
    getAllJobPosts: "/job-post/getAll",
    getJobPostById: "/job-post/get",
    addJobPost: "/job-post/create",
    updateJobPost: "/job-post/update",
    deleteJobPost: "/job-post/delete",
    addNewJobPost: "/add-job-post/create",
    getAllNewJobs: "/add-job-post/getAll",
    deleteNewJobPost: "/add-job-post/delete",
  },
  brouchers: {
    getAllBrouchers: "/broucher/get",
    addBroucher: "/broucher/create",
  },
  certificate: {
    getAllCertificate: "/certificates/get",
    addCertificate: "/certificates/create",
    getCertificatesByStudentId: "/certificates/get",
  },
  Newsletter: {
    getAllNewsletter: "/newsletter/getAll",
    addNewsletter: "/newsletter/add",
  },
  Corporate: {
    getAllCorporate: "/corporate/getAll",
    addCorporate: "/corporate/create",
    updateCorporate: "/corporate/update/:id",
    deleteCorporate: "/corporate/delete",
  },
};
